// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUFmSbAK61tcNAw0vs5ZsJwZkaDgHg7gU',
    appId: '1:1025545644934:android:bdf32f5253b4ed2859da07',
    messagingSenderId: '1025545644934',
    projectId: 'flutter-todo-app-dff66',
    storageBucket: 'flutter-todo-app-dff66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQQssg2fiAGLdmkrIKeZrck55HlCYiK4',
    appId: '1:1025545644934:ios:1fc5d5066499cea659da07',
    messagingSenderId: '1025545644934',
    projectId: 'flutter-todo-app-dff66',
    storageBucket: 'flutter-todo-app-dff66.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXfW8P_pZ6j7pnxUX9r9rzcoVCsBIal_Q',
    appId: '1:1025545644934:web:b8ded055d33e80d459da07',
    messagingSenderId: '1025545644934',
    projectId: 'flutter-todo-app-dff66',
    authDomain: 'flutter-todo-app-dff66.firebaseapp.com',
    storageBucket: 'flutter-todo-app-dff66.firebasestorage.app',
  );
}
